### ISSUE TITLE
Allow non-FHIR files in folders

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/firely-terminal-pipeline#10]
A README.md file stops the validation

> Pushed 1 resource(s) on the stack. 
Accessing terminology and pushing resources to the stack...
Invalid Xml encountered. Details: Data at the root level is invalid. Line 1, position 1.
Error: Process completed with exit code 255.

**Comment by alexzautke** [comment]
@ArdonToonstra Issue cannot be reproduced anymore with latest version. Feel free to re-open the issue if necessary.
