### ISSUE TITLE
Flag to exclude file extensions

### ISSUE THREAD

**Issue by lmvwijk** [FirelyTeam/firely-terminal-pipeline#14]
When I run the JAVA_VALIDATION with .md files in my folder, the validator cannot deal with them. 
![image](https://user-images.githubusercontent.com/96246325/155715746-dcc4f509-2804-4823-b5b6-16422b92135d.png)

As the Java validator itself has no option to exclude file extensions you cannot use JAVA_VALIDATION_OPTIONS to exclude those files or fix it. 
It would be helpful to make it possible to exclude certain file extensions in the validator.

**Comment by alexzautke** [comment]
@lmvwijk The issue should be fixed in version v0.3.3-alpha1. No changes are necessary because now only .json or .xml files are loaded. Can you confirm that the fix is working?
