### ISSUE TITLE
Provide nice colors and statistics for output 

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/firely-terminal-pipeline#17]
For example how https://github.com/pieter-edelman-nictiz/hl7-fhir-validator-action does it:

![image](https://user-images.githubusercontent.com/20518398/159004523-d4622a43-1e8d-441c-b6b2-03c838bd6947.png)

**Comment by alexzautke** [comment]
Feature is implemented in the next release v0.4.7
