### ISSUE TITLE
`fhir check` likely won't ever fail without specifying the `--fail` flag

### ISSUE THREAD

**Issue by chgl** [FirelyTeam/firely-terminal-pipeline#20]
In https://github.com/FirelyTeam/firely-terminal-pipeline/blob/main/action.yml#L241, `fhir check` is ran without specifying the `--fail` flag. This means that even if validation fails, the action still completes successfully, which is most likely not the expected behavior.

See:

```sh
$ fhir validate patient-bundle.json
warning: Evaluation of FhirPath for constraint 'GeburtsdatumRundenAufQuartal' failed: Invocation of function 'matches' failed: Cannot cast from 'Date' to '.NET type String'
error: Instance failed constraint GeburtsdatumRundenAufQuartal "Geburtsdatum darf nicht tagesgenau angegben werden. Das Geburtsdatum MUSS quartalsweise auf-/abgerundet werden."
Result: INVALID

$ echo $?
0
```

(I can't run `check` since its a licensed feature, but I believe the commands behave identically).

**Comment by alexzautke** [comment]
Thanks for the report. This is now fixed in the next version of the validator pipeline v0.4.7 (once the final version is released). The pipeline will continue to run if VALIDATION_CONFORMANCE_DOTNET is set in the EXPECTED_FAILS variable.
