### ISSUE TITLE
Conditional running of action steps could be made more concise using `run.steps[*].if` 

### ISSUE THREAD

**Issue by chgl** [FirelyTeam/firely-terminal-pipeline#21]
I believe the conditional handling inside the action could be implemented more concisely by conditionally running steps based in the input instead of always running and checking inside a shell. E.g. instead of

```yaml
- name: Check if .NET is installed
      run: |
        if $INPUT_DOTNET_VALIDATION_ENABLED || $INPUT_SUSHI_ENABLED; then
          if ! command -v dotnet &> /dev/null
          then
              echo "dotnet could not be found. Please see actions/setup-dotnet to set it up before running this action."
              exit 1
          fi
        fi
      shell: bash
```

```yaml
- name: Check if .NET is installed
  if: ${{ inputs.DOTNET_VALIDATION_ENABLED || inputs.INPUT_SUSHI_ENABLED }}
      run: |
          if ! command -v dotnet &> /dev/null
          then
              echo "dotnet could not be found. Please see actions/setup-dotnet to set it up before running this action."
              exit 1
          fi
      shell: bash
```

This would show the `Check if .NET is installed` step as disabled in the GitHub workflow view.

(As another nit-picky aside: kebab-case for input parameters generally seems more common in GitHub actions)

**Comment by alexzautke** [comment]
Thanks for the suggestion! This would definitely be a nice improvement, I didn't know that this was possible. A PR is very welcome here.

**Comment by alexzautke** [comment]
Just tried this out. Due to the fact that the action is a "composite" action, GitHub will "optimize" the UI and not show any of the individual steps in the log even if you rewrite the conditional check. Closing as not planned.
